// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6CG6S7CTxprP1u-qH47l0Uza_hHnRprw',
    appId: '1:979768481152:web:2f6f9b6ea57d3464f99d65',
    messagingSenderId: '979768481152',
    projectId: 'npsite2024',
    authDomain: 'npsite2024.firebaseapp.com',
    databaseURL: 'https://npsite2024-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'npsite2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaU9MPO-7ih9EQnDdqhO9SMXcrWt48-8o',
    appId: '1:979768481152:android:d2619ccd7a46e34ef99d65',
    messagingSenderId: '979768481152',
    projectId: 'npsite2024',
    databaseURL: 'https://npsite2024-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'npsite2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0E-RUjfLkpDXoSV_cYBgnJliTqawwyM',
    appId: '1:979768481152:ios:f3bd360c6158e303f99d65',
    messagingSenderId: '979768481152',
    projectId: 'npsite2024',
    databaseURL: 'https://npsite2024-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'npsite2024.appspot.com',
    iosBundleId: 'com.example.npsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl0E-RUjfLkpDXoSV_cYBgnJliTqawwyM',
    appId: '1:979768481152:ios:f3bd360c6158e303f99d65',
    messagingSenderId: '979768481152',
    projectId: 'npsite2024',
    databaseURL: 'https://npsite2024-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'npsite2024.appspot.com',
    iosBundleId: 'com.example.npsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6CG6S7CTxprP1u-qH47l0Uza_hHnRprw',
    appId: '1:979768481152:web:0550446a01b76fd9f99d65',
    messagingSenderId: '979768481152',
    projectId: 'npsite2024',
    authDomain: 'npsite2024.firebaseapp.com',
    databaseURL: 'https://npsite2024-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'npsite2024.appspot.com',
  );

}